services:
  - type: web
    name: username-availability-api
    runtime: docker
    plan: free
    rootDir: username-api
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
